//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALQLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonNghiPhep
    {
        public int MaDonNghiPhep { get; set; }
        public int MaLoaiNghiPhep { get; set; }
        public int MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public Nullable<System.DateTime> NgayNghi { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Thu { get; set; }
    
        public virtual LoaiPhep LoaiPhep { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
