//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALQLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuLieuChamCong
    {
        public int MaDuLieuChamCong { get; set; }
        public int MaBangChamCong { get; set; }
        public int MaLoaiCa { get; set; }
        public int MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string Thu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public Nullable<int> NgayPhep { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BangChamCong BangChamCong { get; set; }
        public virtual LoaiCa LoaiCa { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
