//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALQLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int MaHopDong { get; set; }
        public int MaNhanVien { get; set; }
        public string TenHopDong { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> LanKy { get; set; }
        public string ThoiHan { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<double> LuongCoBan { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
