//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALQLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBaoNghi
    {
        public int MaThongBao { get; set; }
        public int MaBangChamCong { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual BangChamCong BangChamCong { get; set; }
    }
}
